### ISSUE TITLE
Several ATECC608A manifest

### ISSUE THREAD

**Issue by JAHTKELD** [kmwebnet/ECC608-TNG-Azure-DPS-Connect#1]
Hello: I have bought 100 ATECC608A for 100 diferent board, I have a one manifest for all chips, and you scripts get the pem for each chip. I 'm not very clear but upload each .pem file is the right way for works with this chips? There is no better way for example upload the full manifest file to Azure?

Best Regards

**Comment by cyberomusubi** [comment]
Thank you for your checking.
This was created for testing a few devices, and I think the program on the manufacturer's site will help you register many certificates.
It seems that it is possible to automatically enroll multiple certificates listed in the manifest file with the AWS CLI.
https://github.com/MicrochipTech/cryptoauth_trustplatform_designsuite/blob/master/TrustnGO/05_cloud_connect/notebook/aws/Microchip_manifest_handler.py

Regards,
Kentaro Mitsuyasu

**Comment by cyberomusubi** [comment]
Sorry, I had a mistake.
for Azure, I'm looking at the code below for auto-registration of multiple devices.
https://github.com/MicrochipTech/cryptoauth_trustplatform_designsuite/blob/master/TrustnGO/05_cloud_connect/notebook/azure/helper_azure.py

**Comment by JAHTKELD** [comment]
Hello
I I have finally managed to upload the manifest to Azure with the helper_azure.py program and with the .crt file that Microchip has published on the page of the new ATECC608B device.

When trying to connect to Azure I get error

![image](https://user-images.githubusercontent.com/52447301/126309976-181560c0-cf0d-435c-abc6-4177271e5a36.png)

But if I do individual enrollment as you explain in your document, everything works correctly, what can be the difference between the two ways of registering the device?

Thanks

**Comment by JAHTKELD** [comment]
Hello

I found at the Device Explorer utility two diferent line for the my device.
![image](https://user-images.githubusercontent.com/52447301/126327293-c31a26e8-b489-4099-b645-54faaf052ff1.png)

very strange.

**Comment by JAHTKELD** [comment]
Hello
I think that the problem is that the helper_azure.py register the devices at the IoThub not at the DPS service, the I need to use

**iotHubClientHandle = IoTHubClient_LL_CreateFromConnectionString(connectionString, MQTT_Protocol))**

and not use the DPS service

**device_ll_handle = IoTHubDeviceClient_LL_CreateFromDeviceAuth(user_ctx.iothub_uri, user_ctx.device_id, iothub_transport)**

Then, I need to remove de DPS service for your program and look for the device_id and device_key to build the connectionstrint  

The two line in the Device explorer are the IotHup register from helper_azure.py and the DPS register from your metode

**Comment by JAHTKELD** [comment]
Hello:

Sorry I have wrong.   

I have to use the 

**device_ll_handle = IoTHubDeviceClient_LL_CreateFromDeviceAuth(user_ctx.iothub_uri, user_ctx.device_id, iothub_transport)**

but the url is the IotHub url, not de DPS service url, and the device_id is the  chip serial number.

Ah, and also remove the DPS service from your program.

Then , it works.

Thanks

**Comment by cyberomusubi** [comment]
Hello.
Yes, as you've noticed, my project first registers the certificate with Azure DPS and provisions it to Azure IoT Hub.
If the provisioning is successful, discard the connection handle and try connecting to Azure IoT Hub again.

I misunderstood the Microchip sample.
It is the operation of registering the certificate directly to Azure IoT Hub.
In that case, you should connect directly to Azure IoT Hub instead of DPS.
